name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - '.gitmodules'
      - 'TalentMatch'
      - 'TalentMatch/**'
      - 'TalentMatch/Dockerfile'
      - 'Front-TalentMatch'
      - 'Front-TalentMatch/**'
      - 'Front-TalentMatch/Dockerfile'
      - '.github/workflows/ci-cd.yml'
      - 'docker-compose.yml'

permissions:
  contents: read
  packages: write

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout monorepo + submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend (TalentMatch)
        uses: docker/build-push-action@v5
        with:
          context: ./TalentMatch
          file: ./TalentMatch/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/talentmatch-back:latest
            ${{ secrets.DOCKER_USERNAME }}/talentmatch-back:${{ github.sha }}
          cache-from: type=gha,scope=tm-back
          cache-to: type=gha,mode=max,scope=tm-back
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=TalentMatch Backend
            org.opencontainers.image.created=${{ github.run_id }}


      - name: Build & Push Frontend (Front-TalentMatch)
        uses: docker/build-push-action@v5
        with:
          context: ./Front-TalentMatch
          file: ./Front-TalentMatch/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/talentmatch-front:latest
            ${{ secrets.DOCKER_USERNAME }}/talentmatch-front:${{ github.sha }}
          cache-from: type=gha,scope=tm-front
          cache-to: type=gha,mode=max,scope=tm-front
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=TalentMatch Frontend
            org.opencontainers.image.created=${{ github.run_id }}
